### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [velipso/polybooljs#20]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by voidqk** [comment]
sure submit a PR I'll take a look

**Comment by geopic** [comment]
I'll get started on it now.

**Comment by velipso** [comment]
I ported this library to typescript, here: https://github.com/velipso/polybool
