### ISSUE TITLE
Feature Request: a way to cleanup polygons with zero-length segments

### ISSUE THREAD

**Issue by adamwong246** [velipso/polybooljs#31]
I'm having a hard time finding an epsilon that fits my data. How hard would it be to implement something that simply removes zero-length segments from the polygon?

**Comment by velipso** [comment]
I haven't looked at it in a long time, but if I remember correctly, it's not that simple.

The zero-length segments can't simply be ignored, that's just one side effect of a series of bad calculations, based on a bad epsilon.

You might want to try PR #8 which some people have had better luck with.
