### ISSUE TITLE
I made a demo game based on polybooljs, looking for performance improvements.

### ISSUE THREAD

**Issue by adamwong246** [velipso/polybooljs#32]
http://adamwong246.github.io/blog/44-Duskers-like-V2/duskersV2.html
https://github.com/adamwong246/SpaceTrash/tree/fov/src/apps/experiments/rotFovReact

I am looking for ANY improvements I can make to performance, specifically [this line](https://github.com/adamwong246/SpaceTrash/blob/fov/src/apps/experiments/rotFovReact/src/AppInferno.js#L243)

**Comment by velipso** [comment]
PR #28 has some performance improvements, you might want to check out

cool demo btw!
