### ISSUE TITLE
Consider adding line segments

### ISSUE THREAD

**Issue by lostPixels** [velipso/polybooljs#34]
I was trying to use PolyBool to do a boolean operation on a line and couldnt quite get it to work. Here's what I was going for, notice how the second shape only has two points. This is for an art project, and suggestions would be greatly appreciated!
`
const shape1 = {
        regions: [[
            [100,100],
            [200,100],
            [200,200],
            [100,200],
            [100,100]
        ]],
        inverted: false
    }

    const shape2 = {
        regions: [[
            [50,50],
            [300,300]
        ]],
        inverted: false
    }

   
    const t = PolyBool.difference(shape1, shape2);
`

**Comment by velipso** [comment]
Hmmm, it seems like overkill if you're just clipping a line... a lot of the complexity of this library is around figuring out which sides are considered inside or outside the clipping area.

I don't know of any libraries that support line vs polygon off the top of my head.  I bet if you search around you can find something though.

**Comment by lostPixels** [comment]
Fair enough. I actually havent been able to locate anything after a day or two of googling, so I opened this SO question to get other opinions. https://stackoverflow.com/questions/68382197/clip-a-line-by-a-polygon-in-javascript It seems like someone out there has had this use case before and I'm hoping they'll chime in.
