### ISSUE TITLE
Cut polygon by line 

### ISSUE THREAD

**Issue by mohammedX6** [velipso/polybooljs#37]
is this library supports cutting polygon with a line ?, Like this : 

![5kadB](https://user-images.githubusercontent.com/24648104/140280080-d4dd0e8a-7baf-4b05-8d45-c23141691b66.png)

**Comment by velipso** [comment]
no... you might be able to make the library do that by converting the line into a polygon and performing a union operation... but that is probably really inefficient.

**Comment by mohammedX6** [comment]
Oh thank you now it's working as intended.
