### ISSUE TITLE
python port

### ISSUE THREAD

**Issue by KaivnD** [velipso/polybooljs#41]
Hi! 
here is [python port](https://github.com/KaivnD/pypolybool)

**Comment by velipso** [comment]
cool I added it to the readme, thanks!

**Comment by KaivnD** [comment]
@velipso  👍🏻 

by the way, I think I have trouble with implement union a list of polygons together, like this

```js
// works AND efficient
var segments = PolyBool.segments(polygons[0]);
for (var i = 1; i < polygons.length; i++){
  var seg2 = PolyBool.segments(polygons[i]);
  var comb = PolyBool.combine(segments, seg2);
  segments = PolyBool.selectUnion(comb);
}
return PolyBool.polygon(segments);
```

on js side works perfect, but when I do same thing in python, missing one region, I couldn't find where am I doing wrong.
could you take a look, if it's ok?

here is relevant issue https://github.com/KaivnD/pypolybool/issues/1

thanks!

**Comment by velipso** [comment]
hmm not sure, I don't really have a good memory of this code to be honest, I just do the bare minimum for maintenance at this point

**Comment by KaivnD** [comment]
@velipso thanks anyway

**Comment by tatarize** [comment]
done
